# Generated by Django 5.0.4 on 2024-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('subtitle', models.CharField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('locations', models.ManyToManyField(to='apps_api.geolocation')),
                ('personas', models.ManyToManyField(to='apps_api.persona')),
            ],
        ),
    ]
